name: Update
on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: master
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: python install
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: update data
        run: |
          mkdir -p data/cartografia/
          python update/convocatorias.py
          python update/cartografia.py
      - name: commit
        run: |
          git config --global user.email "avance_censo@example.com"
          git config --global user.name "avance_censo"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualización"; git push -q "https://$GH_TOKEN@github.com/mauforonda/avance_censo.git" master)
